/**
 * 游戏拟声词与语气词资产词库 (Game Vocal Library)
 * 严格源自《Game Vocal Library.xlsx》，涵盖 10 大类别、78 个细分子类、1560 条拟声语气词
 */

export interface GameVocalSubcategory {
  id: string;
  col: string;
  nameEn: string;
  nameZh: string;
  label: string;
  items: string[];
}

export interface GameVocalCategory {
  id: string;
  key: string;
  title: string;
  nameEn: string;
  nameZh: string;
  emoji: string;
  description: string;
  defaultInstruction: string;
  subcategories: GameVocalSubcategory[];
}

export interface SelectedVocalItem {
  id: string;
  categoryId: string;
  categoryTitle: string;
  subcategoryId: string;
  subcategoryLabel: string;
  text: string;
  instruction?: string;
}

export const GAME_VOCAL_CATEGORIES: GameVocalCategory[] = [
  {
    "id": "cat_1",
    "key": "Attack 攻击",
    "title": "Attack 攻击",
    "nameEn": "Attack",
    "nameZh": "攻击",
    "emoji": "⚔️",
    "description": "Combat efforts for melee, ranged, skill, and special attacks. / 近战、远程、技能与特殊攻击的战斗发声。",
    "defaultInstruction": "短促有力、爆发感强的战斗发力与攻击拟声，动作感明确，爆发短促，无拖泥带水。",
    "subcategories": [
      {
        "id": "sub_1_1",
        "col": "A",
        "nameEn": "Normal Attack",
        "nameZh": "普通攻击",
        "label": "普通攻击 (Normal Attack)",
        "items": [
          "Hah!",
          "Ha!",
          "Hyah!",
          "Hya!",
          "Hup!",
          "Yah!",
          "Tch!",
          "Hng!",
          "Ngh!",
          "Sei!",
          "Tei!",
          "Hwah!",
          "Tyah!",
          "Hiyah!",
          "Shhh!",
          "Hoo!",
          "Tah!",
          "Yaa!",
          "Dah!",
          "Chah!"
        ]
      },
      {
        "id": "sub_1_2",
        "col": "B",
        "nameEn": "Heavy Attack",
        "nameZh": "重攻击",
        "label": "重攻击 (Heavy Attack)",
        "items": [
          "HRAAH!",
          "GRAAH!",
          "HYAAAH!",
          "HAAAH!",
          "NGRAAH!",
          "ROAAAR!",
          "RRGH!",
          "GAAAH!",
          "HYARGH!",
          "RAAAH!",
          "HNNNGH!",
          "GRAAARGH!",
          "HRAAAH!",
          "RRAAH!",
          "KRAAH!",
          "HYYYYAH!",
          "NGHAA!",
          "RAARGH!",
          "HURRAH!",
          "GHHAA!"
        ]
      },
      {
        "id": "sub_1_3",
        "col": "C",
        "nameEn": "Charge / Rush",
        "nameZh": "冲锋 / 突进",
        "label": "冲锋 / 突进 (Charge / Rush)",
        "items": [
          "Charge!!",
          "Forward!!",
          "Rush!!",
          "Go!!",
          "Attack!!",
          "Break through!!",
          "Move!!",
          "Push!!",
          "Out of the way!!",
          "Here I come!!",
          "Full speed!!",
          "Make way!!",
          "Now!!",
          "Let's go!!",
          "Onward!!",
          "Take this!!",
          "Coming through!!",
          "Run them down!!",
          "No stopping!!",
          "Drive forward!!"
        ]
      },
      {
        "id": "sub_1_4",
        "col": "D",
        "nameEn": "Combo / Finisher",
        "nameZh": "连击 / 终结",
        "label": "连击 / 终结 (Combo / Finisher)",
        "items": [
          "One!",
          "Two!",
          "Three!",
          "Again!",
          "Take this!",
          "Finish it!",
          "Here!",
          "And this!",
          "Final blow!",
          "Too slow!",
          "Got you!",
          "Break!",
          "Split!",
          "Cut through!",
          "Last strike!",
          "All in!",
          "That's enough!",
          "End it!",
          "Right there!",
          "Done!"
        ]
      },
      {
        "id": "sub_1_5",
        "col": "E",
        "nameEn": "Ranged / Throw",
        "nameZh": "远程 / 投掷",
        "label": "远程 / 投掷 (Ranged / Throw)",
        "items": [
          "Fire!",
          "Take aim!",
          "Away!",
          "Fly!",
          "Shoot!",
          "Catch this!",
          "Bullseye!",
          "Loose!",
          "Launch!",
          "Right on target!",
          "Go!",
          "Arrow away!",
          "Blast off!",
          "Send it!",
          "Incoming!",
          "Mark!",
          "Strike true!",
          "Let it fly!",
          "Pierce!",
          "Heads up!"
        ]
      },
      {
        "id": "sub_1_6",
        "col": "F",
        "nameEn": "Skill / Magic",
        "nameZh": "技能 / 魔法",
        "label": "技能 / 魔法 (Skill / Magic)",
        "items": [
          "By the flame!",
          "Freeze!",
          "Thunder!",
          "Shadow bind!",
          "Light arise!",
          "Feel this!",
          "Power surge!",
          "Awaken!",
          "Burst!",
          "Rise!",
          "Crush!",
          "Seal!",
          "Break free!",
          "Now vanish!",
          "Storm call!",
          "Solar flare!",
          "Moon strike!",
          "Spirit blaze!",
          "Arcane blast!",
          "Unleash!"
        ]
      },
      {
        "id": "sub_1_7",
        "col": "G",
        "nameEn": "Counter / Parry",
        "nameZh": "反击 / 格挡",
        "label": "反击 / 格挡 (Counter / Parry)",
        "items": [
          "Not today!",
          "Too easy!",
          "Back at you!",
          "Read you!",
          "Try harder!",
          "Mine now!",
          "Your turn!",
          "Denied!",
          "Wide open!",
          "I saw that!",
          "Predictable!",
          "Nice try!",
          "Gotcha!",
          "That's it?",
          "Return to sender!",
          "Wrong move!",
          "My opening!",
          "Too slow!",
          "Perfect!",
          "Counter!"
        ]
      },
      {
        "id": "sub_1_8",
        "col": "H",
        "nameEn": "Exertion",
        "nameZh": "发力",
        "label": "发力 (Exertion)",
        "items": [
          "Hnn!",
          "Nngh!",
          "Hup!",
          "Hah!",
          "Hrrgh!",
          "Nnnh!",
          "Hyup!",
          "Hmph!",
          "Ghh!",
          "Hng!",
          "Uph!",
          "Ngh!",
          "Haa!",
          "Hrr!",
          "Hngh!",
          "Urgh!",
          "Huh!",
          "Nnngh!",
          "Hya!",
          "Hrrraah!"
        ]
      }
    ]
  },
  {
    "id": "cat_2",
    "key": "Hit 受击",
    "title": "Hit 受击",
    "nameEn": "Hit",
    "nameZh": "受击",
    "emoji": "💥",
    "description": "Damage reactions from light impacts to elemental and status effects. / 从轻微受击到元素与异常状态的伤害反应。",
    "defaultInstruction": "受到沉重打击时的本能痛苦闷哼与短促叫声，真实身体受挫感，撕裂感与窒息痛感。",
    "subcategories": [
      {
        "id": "sub_2_1",
        "col": "A",
        "nameEn": "Light Hit",
        "nameZh": "轻度受击",
        "label": "轻度受击 (Light Hit)",
        "items": [
          "Ugh!",
          "Ack!",
          "Ow!",
          "Gah!",
          "Hn!",
          "Tch!",
          "Urk!",
          "Oof!",
          "Hey!",
          "Ah!",
          "Ngh!",
          "Hrk!",
          "Huh!",
          "Ghk!",
          "Ouch!",
          "Unh!",
          "Tsk!",
          "Hk!",
          "Nn!",
          "Gck!"
        ]
      },
      {
        "id": "sub_2_2",
        "col": "B",
        "nameEn": "Heavy Hit",
        "nameZh": "重度受击",
        "label": "重度受击 (Heavy Hit)",
        "items": [
          "Aargh!",
          "Ghaa!",
          "Urrgh!",
          "Nngh!",
          "Gahh!",
          "HRAAGH!",
          "Aaah!",
          "Grrgh!",
          "Uuugh!",
          "Rrgh!",
          "Agh!",
          "Ghaaah!",
          "Hnnngh!",
          "Argh!",
          "Nghaa!",
          "Grrraa!",
          "Oww!",
          "Urrrgh!",
          "HRAH!",
          "Aaagh!"
        ]
      },
      {
        "id": "sub_2_3",
        "col": "C",
        "nameEn": "Critical Hit",
        "nameZh": "暴击受击",
        "label": "暴击受击 (Critical Hit)",
        "items": [
          "What?!",
          "No!",
          "Gah!",
          "That hurt!",
          "Aaaagh!",
          "Not good!",
          "Hnngh!",
          "I felt that!",
          "Damn!",
          "Too much!",
          "Agh!",
          "My guard!",
          "Grrgh!",
          "Seriously?!",
          "Ngh!",
          "That cuts deep!",
          "Urgh!",
          "Not there!",
          "Ow!",
          "HRAAGH!"
        ]
      },
      {
        "id": "sub_2_4",
        "col": "D",
        "nameEn": "Knockback / Launch",
        "nameZh": "击退 / 击飞",
        "label": "击退 / 击飞 (Knockback / Launch)",
        "items": [
          "Whoa!",
          "Aaah!",
          "I'm flying!",
          "Not again!",
          "Huh?!",
          "Gah!",
          "Look out!",
          "Aah!",
          "No no no!",
          "Hnngh!",
          "Catch me!",
          "Too far!",
          "Oof!",
          "Hey!",
          "Urrgh!",
          "Whoa whoa!",
          "I can't stop!",
          "Aaaah!",
          "Ghk!",
          "Help!"
        ]
      },
      {
        "id": "sub_2_5",
        "col": "E",
        "nameEn": "Stagger / Knockdown",
        "nameZh": "失衡 / 击倒",
        "label": "失衡 / 击倒 (Stagger / Knockdown)",
        "items": [
          "I'm down!",
          "Oof!",
          "Not good!",
          "Get up!",
          "Ugh...",
          "My legs!",
          "Hnngh...",
          "Too dizzy!",
          "Gah!",
          "Hold on...",
          "Can't move!",
          "That shook me!",
          "Ngh...",
          "I slipped!",
          "Need a second!",
          "Hrk!",
          "On the ground!",
          "Not now!",
          "Agh...",
          "Steady..."
        ]
      },
      {
        "id": "sub_2_6",
        "col": "F",
        "nameEn": "Fire / Burn",
        "nameZh": "火焰 / 灼烧",
        "label": "火焰 / 灼烧 (Fire / Burn)",
        "items": [
          "Hot!",
          "I'm burning!",
          "Aah, hot!",
          "Get it off!",
          "Too hot!",
          "Fire!",
          "It burns!",
          "Ow ow ow!",
          "Smoke!",
          "Gah!",
          "Flames!",
          "My skin!",
          "Put it out!",
          "Hah! Hot!",
          "Scorching!",
          "Aargh!",
          "Not the fire!",
          "Burning up!",
          "Help!",
          "No more heat!"
        ]
      },
      {
        "id": "sub_2_7",
        "col": "G",
        "nameEn": "Ice / Shock / Poison",
        "nameZh": "冰冻 / 电击 / 中毒",
        "label": "冰冻 / 电击 / 中毒 (Ice / Shock / Poison)",
        "items": [
          "Cold!",
          "So cold!",
          "Can't feel my hands!",
          "Bzzzt!",
          "Agh, shock!",
          "It stings!",
          "Poisoned!",
          "My body...",
          "Numb!",
          "Static!",
          "Frozen!",
          "Tingly...",
          "Gah!",
          "I can't breathe!",
          "Chills!",
          "Venom!",
          "My muscles!",
          "Argh!",
          "Paralyzed!",
          "This isn't good!"
        ]
      },
      {
        "id": "sub_2_8",
        "col": "H",
        "nameEn": "Guard Break",
        "nameZh": "破防",
        "label": "破防 (Guard Break)",
        "items": [
          "My guard!",
          "Broken!",
          "I was open!",
          "No shield!",
          "Gah!",
          "That got through!",
          "Can't block!",
          "Wide open!",
          "Hnngh!",
          "Defense down!",
          "My stance!",
          "I slipped!",
          "Not now!",
          "Guard's gone!",
          "Ugh!",
          "Too strong!",
          "My arm!",
          "No cover!",
          "Agh!",
          "Exposed!"
        ]
      }
    ]
  },
  {
    "id": "cat_3",
    "key": "Death 死亡",
    "title": "Death 死亡",
    "nameEn": "Death",
    "nameZh": "死亡",
    "emoji": "☠️",
    "description": "Final reactions and fades for human, creature, and dramatic defeats. / 人类、生物与戏剧化战败的终结反应与渐弱声音。",
    "defaultInstruction": "生命流逝时的绝望倒地发声，重伤脱力的叹息、断气与最后一息。",
    "subcategories": [
      {
        "id": "sub_3_1",
        "col": "A",
        "nameEn": "Quick Death",
        "nameZh": "快速死亡",
        "label": "快速死亡 (Quick Death)",
        "items": [
          "Agh!",
          "Ack!",
          "Gah!",
          "Ugh!",
          "No!",
          "Argh!",
          "Hrk!",
          "Ghk!",
          "Ah!",
          "Oof!",
          "Ngh!",
          "Urk!",
          "Aah!",
          "Grrh!",
          "Huh!",
          "Tch!",
          "Nn!",
          "Hng!",
          "Urrgh!",
          "Aaagh!"
        ]
      },
      {
        "id": "sub_3_2",
        "col": "B",
        "nameEn": "Dramatic Death",
        "nameZh": "戏剧化死亡",
        "label": "戏剧化死亡 (Dramatic Death)",
        "items": [
          "Nooo!",
          "This can't be...",
          "Not yet!",
          "I won't... fall...",
          "Impossible!",
          "Aaaaargh!",
          "My time...",
          "I failed...",
          "Not like this!",
          "Remember me...",
          "I was so close...",
          "No... no...",
          "It's over...",
          "Forgive me...",
          "I can't...",
          "I won't give in...",
          "Farewell...",
          "So this is it...",
          "Not finished...",
          "Avenge me..."
        ]
      },
      {
        "id": "sub_3_3",
        "col": "C",
        "nameEn": "Heavy / Crushed",
        "nameZh": "重压 / 碾压",
        "label": "重压 / 碾压 (Heavy / Crushed)",
        "items": [
          "GHHAA!",
          "Too heavy!",
          "Can't breathe!",
          "Crushed!",
          "Aargh!",
          "Get it off!",
          "My ribs!",
          "Hnngh!",
          "No room!",
          "Help me!",
          "Urrgh!",
          "I'm pinned!",
          "Graaah!",
          "It hurts!",
          "Can't move!",
          "Agh!",
          "So heavy...",
          "Nnngh!",
          "Not enough strength...",
          "Ghk!"
        ]
      },
      {
        "id": "sub_3_4",
        "col": "D",
        "nameEn": "Fall / Void",
        "nameZh": "坠落 / 虚空",
        "label": "坠落 / 虚空 (Fall / Void)",
        "items": [
          "Aaaah!",
          "I'm falling!",
          "No no no!",
          "Too far down!",
          "Help!",
          "Whoa!",
          "Not the edge!",
          "Aaahhh!",
          "Catch me!",
          "Goodbye!",
          "I can't stop!",
          "No ground!",
          "This is bad!",
          "Falling!",
          "Aaaaargh!",
          "Wait!",
          "Not like this!",
          "The drop!",
          "I slipped!",
          "No!"
        ]
      },
      {
        "id": "sub_3_5",
        "col": "E",
        "nameEn": "Explosion",
        "nameZh": "爆炸",
        "label": "爆炸 (Explosion)",
        "items": [
          "Whoa!",
          "Incoming!",
          "Aaaagh!",
          "Boom!",
          "No time!",
          "Get down!",
          "Too close!",
          "Blast!",
          "Gah!",
          "I'm hit!",
          "Fireball!",
          "Aaah!",
          "That was huge!",
          "No cover!",
          "Kaboom!",
          "Urrgh!",
          "Run!",
          "Oh no!",
          "The bomb!",
          "HRAAGH!"
        ]
      },
      {
        "id": "sub_3_6",
        "col": "F",
        "nameEn": "Fade / Last Breath",
        "nameZh": "渐弱 / 最后一息",
        "label": "渐弱 / 最后一息 (Fade / Last Breath)",
        "items": [
          "...",
          "Hah...",
          "I...",
          "So tired...",
          "Can't go on...",
          "Not now...",
          "Stay awake...",
          "Just a moment...",
          "Hhh...",
          "My strength...",
          "It's fading...",
          "Don't leave me...",
          "I see...",
          "Cold...",
          "I'm sorry...",
          "Quiet now...",
          "No more...",
          "Haa...",
          "At last...",
          "Goodnight..."
        ]
      }
    ]
  },
  {
    "id": "cat_4",
    "key": "Movement 移动",
    "title": "Movement 移动",
    "nameEn": "Movement",
    "nameZh": "移动",
    "emoji": "🏃",
    "description": "Efforts and reactions for traversal, balance, jumps, and physical actions. / 移动、平衡、跳跃与体力动作的发声和反应。",
    "defaultInstruction": "机动动作时的呼吸与轻微发力声，灵敏轻盈，短促利落，节奏分明。",
    "subcategories": [
      {
        "id": "sub_4_1",
        "col": "A",
        "nameEn": "Jump",
        "nameZh": "跳跃",
        "label": "跳跃 (Jump)",
        "items": [
          "Hup!",
          "Hyup!",
          "Yah!",
          "Hop!",
          "Here goes!",
          "Up!",
          "Leap!",
          "Hah!",
          "Woo!",
          "Jump!",
          "Hya!",
          "Yoop!",
          "Boing!",
          "Going up!",
          "All right!",
          "One, two!",
          "Ha!",
          "Watch this!",
          "Higher!",
          "Now!"
        ]
      },
      {
        "id": "sub_4_2",
        "col": "B",
        "nameEn": "Land",
        "nameZh": "落地",
        "label": "落地 (Land)",
        "items": [
          "Oof!",
          "Hup!",
          "There!",
          "Safe!",
          "Easy...",
          "Thud!",
          "Hah!",
          "Got it!",
          "Steady!",
          "Ngh!",
          "On my feet!",
          "That works!",
          "Down!",
          "Hmph!",
          "All good!",
          "Soft landing!",
          "Whoops!",
          "Made it!",
          "Ha!",
          "Not bad!"
        ]
      },
      {
        "id": "sub_4_3",
        "col": "C",
        "nameEn": "Climb / Pull",
        "nameZh": "攀爬 / 拉拽",
        "label": "攀爬 / 拉拽 (Climb / Pull)",
        "items": [
          "Hup!",
          "Heave!",
          "Almost there!",
          "Pull!",
          "Hng!",
          "One more!",
          "Up we go!",
          "Ngh!",
          "Got a hold!",
          "Don't slip!",
          "Higher!",
          "Ha!",
          "Reach!",
          "Keep moving!",
          "Hrrgh!",
          "Grab it!",
          "Just up!",
          "Hold on!",
          "Nearly!",
          "Made it!"
        ]
      },
      {
        "id": "sub_4_4",
        "col": "D",
        "nameEn": "Sprint / Dash",
        "nameZh": "冲刺 / 闪避",
        "label": "冲刺 / 闪避 (Sprint / Dash)",
        "items": [
          "Go!",
          "Faster!",
          "Move!",
          "Hah!",
          "Hup!",
          "Out of the way!",
          "Can't stop!",
          "Keep up!",
          "Run!",
          "Now!",
          "Here I go!",
          "Quick!",
          "Full speed!",
          "Swift!",
          "Dash!",
          "Make room!",
          "On the move!",
          "No slowing down!",
          "Let's fly!",
          "Go go go!"
        ]
      },
      {
        "id": "sub_4_5",
        "col": "E",
        "nameEn": "Dodge / Roll",
        "nameZh": "躲闪 / 翻滚",
        "label": "躲闪 / 翻滚 (Dodge / Roll)",
        "items": [
          "Whoop!",
          "Missed me!",
          "Hup!",
          "Too slow!",
          "Out!",
          "Roll!",
          "Close one!",
          "Ha!",
          "Not today!",
          "Move!",
          "Duck!",
          "Slide!",
          "There!",
          "Whoosh!",
          "Hah!",
          "Back off!",
          "Almost!",
          "Nope!",
          "Behind you!",
          "Clear!"
        ]
      },
      {
        "id": "sub_4_6",
        "col": "F",
        "nameEn": "Lift / Push",
        "nameZh": "举起 / 推动",
        "label": "举起 / 推动 (Lift / Push)",
        "items": [
          "Heave!",
          "Hnn!",
          "Ngh!",
          "Push!",
          "Hup!",
          "Too heavy!",
          "Come on!",
          "Move it!",
          "Hrrgh!",
          "Just a bit!",
          "Lift!",
          "Steady!",
          "Ghh!",
          "Almost!",
          "One more!",
          "Hah!",
          "Don't drop it!",
          "Together!",
          "Now!",
          "There!"
        ]
      },
      {
        "id": "sub_4_7",
        "col": "G",
        "nameEn": "Slip / Balance",
        "nameZh": "滑倒 / 平衡",
        "label": "滑倒 / 平衡 (Slip / Balance)",
        "items": [
          "Whoa!",
          "Easy!",
          "Careful!",
          "I'm slipping!",
          "Not the edge!",
          "Steady!",
          "Ah!",
          "Whoa whoa!",
          "Got it!",
          "Close!",
          "Don't fall!",
          "Hup!",
          "Balance!",
          "Aah!",
          "Nearly lost it!",
          "Hold on!",
          "Nope!",
          "Tightrope time!",
          "Phew!",
          "Safe!"
        ]
      },
      {
        "id": "sub_4_8",
        "col": "H",
        "nameEn": "Swim / Dive",
        "nameZh": "游泳 / 潜水",
        "label": "游泳 / 潜水 (Swim / Dive)",
        "items": [
          "Splash!",
          "Hah!",
          "Down we go!",
          "Breathe!",
          "Kick!",
          "Under!",
          "Swim!",
          "Whoo!",
          "Deep breath!",
          "Dive!",
          "Keep moving!",
          "Gasp!",
          "Up!",
          "Water's cold!",
          "Stroke!",
          "Almost there!",
          "Hold it!",
          "Surface!",
          "Hup!",
          "Phew!"
        ]
      }
    ]
  },
  {
    "id": "cat_5",
    "key": "Emotion 情绪",
    "title": "Emotion 情绪",
    "nameEn": "Emotion",
    "nameZh": "情绪",
    "emoji": "🎭",
    "description": "Expressive reads for character personality, tension, celebration, and social moments. / 用于角色个性、紧张、庆祝与社交场景的情绪表达。",
    "defaultInstruction": "极具角色性格特征的真情实感流露，情绪饱满生动，富有戏剧张力。",
    "subcategories": [
      {
        "id": "sub_5_1",
        "col": "A",
        "nameEn": "Joy / Victory",
        "nameZh": "喜悦 / 胜利",
        "label": "喜悦 / 胜利 (Joy / Victory)",
        "items": [
          "Yes!",
          "Woohoo!",
          "We did it!",
          "All right!",
          "Ha!",
          "Perfect!",
          "That's how!",
          "Nice!",
          "I knew it!",
          "Victory!",
          "Amazing!",
          "Finally!",
          "Yeah!",
          "Lucky me!",
          "What a rush!",
          "Got it!",
          "Brilliant!",
          "Easy!",
          "Fantastic!",
          "Hah!"
        ]
      },
      {
        "id": "sub_5_2",
        "col": "B",
        "nameEn": "Anger",
        "nameZh": "愤怒",
        "label": "愤怒 (Anger)",
        "items": [
          "Grr!",
          "Enough!",
          "You'll pay!",
          "Get back here!",
          "I said stop!",
          "Not funny!",
          "Move!",
          "Don't test me!",
          "I'm done!",
          "Back off!",
          "How dare you!",
          "No more games!",
          "You're finished!",
          "Try me!",
          "That was a mistake!",
          "I won't forgive this!",
          "Out of my way!",
          "Hmph!",
          "Raaah!",
          "Come on!"
        ]
      },
      {
        "id": "sub_5_3",
        "col": "C",
        "nameEn": "Surprise",
        "nameZh": "惊讶",
        "label": "惊讶 (Surprise)",
        "items": [
          "Huh?!",
          "What?!",
          "Whoa!",
          "Really?!",
          "No way!",
          "Oh!",
          "Ah?!",
          "You what?",
          "Is that...?",
          "Wait!",
          "Seriously?",
          "How did...?",
          "Oh no!",
          "Well, well!",
          "I didn't expect that!",
          "Hey!",
          "That's new!",
          "Goodness!",
          "Impossible!",
          "Wow!"
        ]
      },
      {
        "id": "sub_5_4",
        "col": "D",
        "nameEn": "Fear / Panic",
        "nameZh": "恐惧 / 惊慌",
        "label": "恐惧 / 惊慌 (Fear / Panic)",
        "items": [
          "No!",
          "Help!",
          "Stay back!",
          "Run!",
          "What was that?!",
          "Don't come closer!",
          "I'm scared!",
          "Please no!",
          "Not again!",
          "Get away!",
          "Someone!",
          "We need to leave!",
          "I can't look!",
          "This is bad!",
          "Hide!",
          "Oh no no no!",
          "Don't touch me!",
          "It's coming!",
          "I don't like this!",
          "Aaaah!"
        ]
      },
      {
        "id": "sub_5_5",
        "col": "E",
        "nameEn": "Sadness",
        "nameZh": "悲伤",
        "label": "悲伤 (Sadness)",
        "items": [
          "Oh...",
          "I see...",
          "That's too bad.",
          "I'm sorry.",
          "Not today...",
          "I tried.",
          "Why...?",
          "It hurts...",
          "I miss them.",
          "What now?",
          "I understand.",
          "This isn't fair.",
          "Goodbye.",
          "I let you down.",
          "I hoped...",
          "Maybe next time.",
          "No words...",
          "I'm tired.",
          "Please...",
          "Hah..."
        ]
      },
      {
        "id": "sub_5_6",
        "col": "F",
        "nameEn": "Taunt / Smirk",
        "nameZh": "挑衅 / 冷笑",
        "label": "挑衅 / 冷笑 (Taunt / Smirk)",
        "items": [
          "Heh.",
          "Is that all?",
          "Too easy.",
          "Try harder.",
          "Come on!",
          "You missed.",
          "Over here!",
          "Catch me!",
          "Nice try.",
          "Slow down.",
          "That tickled.",
          "Boring.",
          "You're predictable.",
          "I expected better.",
          "Keep dreaming.",
          "Almost impressive.",
          "My turn.",
          "Bring it.",
          "Hmph.",
          "Hehehe."
        ]
      },
      {
        "id": "sub_5_7",
        "col": "G",
        "nameEn": "Laugh / Chuckle",
        "nameZh": "大笑 / 轻笑",
        "label": "大笑 / 轻笑 (Laugh / Chuckle)",
        "items": [
          "Haha!",
          "Hahaha!",
          "Heh heh!",
          "Hoho!",
          "Pfft!",
          "Ha!",
          "Hehehe!",
          "Hah hah!",
          "Oh, that's good!",
          "Ha ha ha!",
          "Mwahaha!",
          "Keh!",
          "Hmph-heh.",
          "Teehee!",
          "Oh dear!",
          "Heh!",
          "Hahaha, yes!",
          "Ha! Brilliant!",
          "Hoh!",
          "Heheheh!"
        ]
      },
      {
        "id": "sub_5_8",
        "col": "H",
        "nameEn": "Breath / Effort",
        "nameZh": "喘息 / 发力",
        "label": "喘息 / 发力 (Breath / Effort)",
        "items": [
          "Hah...",
          "Huff...",
          "Pant...",
          "Gasp...",
          "Hhh...",
          "Wheeze...",
          "Deep breath...",
          "Phew...",
          "Haa...",
          "Huh...",
          "Huff huff...",
          "Easy...",
          "Catch breath...",
          "Steady...",
          "In... out...",
          "Hah!",
          "Gasp!",
          "Breathe...",
          "Phew!",
          "Hnn..."
        ]
      }
    ]
  },
  {
    "id": "cat_6",
    "key": "Beast 野兽",
    "title": "Beast 野兽",
    "nameEn": "Beast",
    "nameZh": "野兽",
    "emoji": "🐺",
    "description": "Animalistic vocalizations for friendly, hostile, hunting, and distressed creatures. / 适用于友好、敌对、狩猎与受伤动物的拟声词。",
    "defaultInstruction": "野兽喉部深处的低沉嘶吼与咆哮，带有猛兽压迫感与尖锐齿音、兽性本能。",
    "subcategories": [
      {
        "id": "sub_6_1",
        "col": "A",
        "nameEn": "Growl",
        "nameZh": "低吼",
        "label": "低吼 (Growl)",
        "items": [
          "Grrr...",
          "Grrrr!",
          "Rrrr...",
          "GRAH!",
          "Rrrgh!",
          "Grr!",
          "Rrrrr...",
          "Grah...",
          "Rrrraah!",
          "Grrrah!",
          "Rrrowl...",
          "Grrrgh!",
          "Rrr!",
          "Gnarl...",
          "Grrrrr!",
          "Rrrgh...",
          "Grrr!",
          "Raaawr...",
          "Grrraah!",
          "Rrrrrgh!"
        ]
      },
      {
        "id": "sub_6_2",
        "col": "B",
        "nameEn": "Roar",
        "nameZh": "咆哮",
        "label": "咆哮 (Roar)",
        "items": [
          "RAWR!",
          "ROAAAR!",
          "GRAAAH!",
          "RRAAAH!",
          "RRAWR!",
          "GROOOAR!",
          "RRAAAGH!",
          "RAAAWR!",
          "GRAWR!",
          "ROAR!!",
          "RRAARGH!",
          "GRAAAARR!",
          "RROOOAR!",
          "RAAAGH!",
          "VRAAAARGH!",
          "RRAH!",
          "ROOOARR!",
          "GRAAWR!",
          "RRAAAWR!",
          "ROAAARGH!"
        ]
      },
      {
        "id": "sub_6_3",
        "col": "C",
        "nameEn": "Snarl / Threat",
        "nameZh": "龇牙 / 威胁",
        "label": "龇牙 / 威胁 (Snarl / Threat)",
        "items": [
          "Sssnarl!",
          "Hrrr...",
          "Rrrah!",
          "Krrr!",
          "Sss!",
          "Rrrk!",
          "Hisss!",
          "Grrr!",
          "Rrrow!",
          "Krah!",
          "Hrrgh!",
          "Ssssk!",
          "Rrraah!",
          "Grrak!",
          "Hrrr!",
          "Sssnar!",
          "Rrr!",
          "Krrrah!",
          "Hssss!",
          "Grrrgh!"
        ]
      },
      {
        "id": "sub_6_4",
        "col": "D",
        "nameEn": "Pain / Yelp",
        "nameZh": "疼痛 / 呜咽",
        "label": "疼痛 / 呜咽 (Pain / Yelp)",
        "items": [
          "Yip!",
          "Awrf!",
          "Rrgh!",
          "Yowl!",
          "Eek!",
          "Raa!",
          "Whine...",
          "Yelp!",
          "Grrk!",
          "Awooo!",
          "Rrraa!",
          "Krr!",
          "Yip yip!",
          "Mrrrow!",
          "Arf!",
          "Rrgh...",
          "Wail!",
          "Kyaa!",
          "Awoo!",
          "Grr!"
        ]
      },
      {
        "id": "sub_6_5",
        "col": "E",
        "nameEn": "Call / Howl",
        "nameZh": "呼唤 / 嚎叫",
        "label": "呼唤 / 嚎叫 (Call / Howl)",
        "items": [
          "Awooo!",
          "Raaaw!",
          "Kraaa!",
          "Hoooo!",
          "Awoo-woo!",
          "Rrrr-rah!",
          "Mraow!",
          "Caw!",
          "Kreee!",
          "Oooo!",
          "Raaawr!",
          "Awooooo!",
          "Kraa!",
          "Hoo!",
          "Rrrrroo!",
          "Mrrrrow!",
          "Caw-caw!",
          "Kree!",
          "Owww!",
          "Raaah!"
        ]
      },
      {
        "id": "sub_6_6",
        "col": "F",
        "nameEn": "Bark / Chirp",
        "nameZh": "吠叫 / 鸣叫",
        "label": "吠叫 / 鸣叫 (Bark / Chirp)",
        "items": [
          "Arf!",
          "Woof!",
          "Yip!",
          "Ruff!",
          "Bark!",
          "Yap!",
          "Chirp!",
          "Tweet!",
          "Kek!",
          "Caw!",
          "Trill!",
          "Peep!",
          "Rruff!",
          "Yip-yip!",
          "Bork!",
          "Krr!",
          "Cheep!",
          "Squawk!",
          "Hoot!",
          "Mew!"
        ]
      },
      {
        "id": "sub_6_7",
        "col": "G",
        "nameEn": "Idle / Content",
        "nameZh": "待机 / 满足",
        "label": "待机 / 满足 (Idle / Content)",
        "items": [
          "Mrrr...",
          "Purr...",
          "Huff...",
          "Sniff...",
          "Rumble...",
          "Mmmrr...",
          "Chuff...",
          "Hrrm...",
          "Nuzzle...",
          "Mrrp!",
          "Huff huff...",
          "Prrr...",
          "Snort...",
          "Mrrrow...",
          "Chirr...",
          "Rrrum...",
          "Hmmm...",
          "Puff...",
          "Nnrr...",
          "Mrr!"
        ]
      },
      {
        "id": "sub_6_8",
        "col": "H",
        "nameEn": "Attack Lunge",
        "nameZh": "攻击 / 扑击",
        "label": "攻击 / 扑击 (Attack Lunge)",
        "items": [
          "RAH!",
          "GRAH!",
          "RRAWR!",
          "KRAA!",
          "HSSS!",
          "Grrrah!",
          "RRAAGH!",
          "Sss!",
          "KRR!",
          "RAAAH!",
          "GRAWR!",
          "Rrrraah!",
          "HRAA!",
          "Krah!",
          "RRAH!",
          "GRAA!",
          "HISS!",
          "Rrgh!",
          "SKRAAA!",
          "ROAR!"
        ]
      }
    ]
  },
  {
    "id": "cat_7",
    "key": "Monster 怪物",
    "title": "Monster 怪物",
    "nameEn": "Monster",
    "nameZh": "怪物",
    "emoji": "👾",
    "description": "Unnatural, supernatural, and boss-scale vocalizations for monsters. / 适用于怪物、超自然与 Boss 级别角色的非自然发声。",
    "defaultInstruction": "非人生物的深沉喉音、尖啸与空灵低语，具有异形感、回响感与非自然压迫感。",
    "subcategories": [
      {
        "id": "sub_7_1",
        "col": "A",
        "nameEn": "Deep Roar",
        "nameZh": "深沉咆哮",
        "label": "深沉咆哮 (Deep Roar)",
        "items": [
          "GROOOOAR...",
          "VRRAAAH!",
          "DRAAAGH!",
          "KROOOOM!",
          "GRAAAARR!",
          "RRRUUUM!",
          "DROOOH!",
          "VRAAARGH!",
          "KRAAAH!",
          "GROOOOM!",
          "RRRAAAH!",
          "DRAAAR!",
          "VROOOAR!",
          "GRAAAH!",
          "KROOOAR!",
          "RRAAUGH!",
          "DROOOOM!",
          "VRAA!",
          "GROAAAR!",
          "KRAAARGH!"
        ]
      },
      {
        "id": "sub_7_2",
        "col": "B",
        "nameEn": "Hiss / Whisper",
        "nameZh": "嘶嘶 / 低语",
        "label": "嘶嘶 / 低语 (Hiss / Whisper)",
        "items": [
          "Ssssss...",
          "Hissss!",
          "Ksssh...",
          "Ssaaar...",
          "Hushhh...",
          "Ssssk!",
          "Zzzh...",
          "Shhh...",
          "Saaah...",
          "Khhhh...",
          "Sssra!",
          "Vsssh...",
          "Hisss...",
          "Sssee...",
          "Kssss!",
          "Zhaaa...",
          "Sssskrr...",
          "Hhhhss...",
          "Sshaa...",
          "Vssss..."
        ]
      },
      {
        "id": "sub_7_3",
        "col": "C",
        "nameEn": "Screech",
        "nameZh": "尖啸",
        "label": "尖啸 (Screech)",
        "items": [
          "SKREEE!",
          "KREEE!",
          "SHRIIIEK!",
          "SRAAAK!",
          "KEEEH!",
          "SKRAAA!",
          "WREEE!",
          "SHEEAA!",
          "KRRREE!",
          "SRAEEK!",
          "KIEEE!",
          "SHRAAA!",
          "REEEE!",
          "SKREEK!",
          "KRAAEEE!",
          "WHEEE!",
          "SRRAAA!",
          "KREEK!",
          "SHRIEE!",
          "SKEEAA!"
        ]
      },
      {
        "id": "sub_7_4",
        "col": "D",
        "nameEn": "Guttural",
        "nameZh": "喉音",
        "label": "喉音 (Guttural)",
        "items": [
          "Ghlrr...",
          "Krrgh...",
          "Uuuhk...",
          "Brrrgh!",
          "Grrlukh...",
          "Hruum...",
          "Khlagh!",
          "Ghul...",
          "Rrrukh!",
          "Blaarg...",
          "Ghrum!",
          "Krrul...",
          "Ughraa...",
          "Brroth...",
          "Ghlak!",
          "Hrruum...",
          "Khluk!",
          "Rrulgh...",
          "Braagh!",
          "Ghrraa..."
        ]
      },
      {
        "id": "sub_7_5",
        "col": "E",
        "nameEn": "Ethereal / Ghost",
        "nameZh": "空灵 / 幽魂",
        "label": "空灵 / 幽魂 (Ethereal / Ghost)",
        "items": [
          "Ooooh...",
          "Waaaiil...",
          "Hollow...",
          "Soooul...",
          "Eeeeer...",
          "Whiiisper...",
          "Aaahhh...",
          "Faaaade...",
          "Mooourn...",
          "Ooooo...",
          "Lost...",
          "Coooome...",
          "Eeeee...",
          "Niiight...",
          "Bewaaare...",
          "Haaunt...",
          "Siiigh...",
          "Wooo...",
          "Dreeeam...",
          "Gooo..."
        ]
      },
      {
        "id": "sub_7_6",
        "col": "F",
        "nameEn": "Spell / Curse",
        "nameZh": "咒语 / 诅咒",
        "label": "咒语 / 诅咒 (Spell / Curse)",
        "items": [
          "Ruin...",
          "Consume...",
          "Kneel...",
          "Perish...",
          "Awaken...",
          "Decay...",
          "Suffer...",
          "Be undone...",
          "The void calls...",
          "Fall...",
          "Doom...",
          "Submit...",
          "Darkness rise...",
          "Break...",
          "Wither...",
          "You are mine...",
          "No escape...",
          "Silence...",
          "Tremble...",
          "Endless night..."
        ]
      },
      {
        "id": "sub_7_7",
        "col": "G",
        "nameEn": "Pain / Defeat",
        "nameZh": "痛苦 / 战败",
        "label": "痛苦 / 战败 (Pain / Defeat)",
        "items": [
          "GRAAAGH!",
          "Vrrrgh...",
          "Krrraah!",
          "NOOOO!",
          "Hsssk!",
          "Draaa...",
          "Ghlrr...",
          "RRAAUGH!",
          "Krooom...",
          "Sss...",
          "Vraah!",
          "Krrgh...",
          "Aaaaar...",
          "Grruum...",
          "Draah...",
          "Khh...",
          "Rrrr...",
          "Voooh...",
          "GRAH!",
          "Ssshhh..."
        ]
      },
      {
        "id": "sub_7_8",
        "col": "H",
        "nameEn": "Idle / Ambient",
        "nameZh": "待机 / 环境音",
        "label": "待机 / 环境音 (Idle / Ambient)",
        "items": [
          "Rumble...",
          "Click...",
          "Sss...",
          "Thrum...",
          "Grrr...",
          "Whisper...",
          "Chitter...",
          "Hollow breath...",
          "Drip...",
          "Rattle...",
          "Buzz...",
          "Skitter...",
          "Murmur...",
          "Groan...",
          "Crackle...",
          "Pulse...",
          "Scrape...",
          "Moan...",
          "Hummm...",
          "Clack..."
        ]
      }
    ]
  },
  {
    "id": "cat_8",
    "key": "Human 人类",
    "title": "Human 人类",
    "nameEn": "Human",
    "nameZh": "人类",
    "emoji": "👤",
    "description": "Human-character vocalizations across common archetypes and conversational beats. / 常见人类角色原型与对话节奏的发声。",
    "defaultInstruction": "自然生动的人声战斗发音与对白质感，咬字清晰，角色特征鲜明。",
    "subcategories": [
      {
        "id": "sub_8_1",
        "col": "A",
        "nameEn": "Male Combat",
        "nameZh": "男性战斗",
        "label": "男性战斗 (Male Combat)",
        "items": [
          "Hah!",
          "Take this!",
          "Raaah!",
          "Not bad!",
          "Come on!",
          "Hup!",
          "Stay down!",
          "Here!",
          "Hng!",
          "Now!",
          "Out of my way!",
          "Gah!",
          "Keep moving!",
          "You asked for it!",
          "Down you go!",
          "Bring it!",
          "Right there!",
          "Too slow!",
          "Hraaah!",
          "Done!"
        ]
      },
      {
        "id": "sub_8_2",
        "col": "B",
        "nameEn": "Female Combat",
        "nameZh": "女性战斗",
        "label": "女性战斗 (Female Combat)",
        "items": [
          "Hyah!",
          "Take this!",
          "Hah!",
          "Not today!",
          "Hup!",
          "Move!",
          "Here I go!",
          "You wish!",
          "Yah!",
          "Try this!",
          "Back off!",
          "Hya!",
          "No mercy!",
          "My turn!",
          "Ha!",
          "Got you!",
          "Keep up!",
          "Hnn!",
          "Out!",
          "Finish it!"
        ]
      },
      {
        "id": "sub_8_3",
        "col": "C",
        "nameEn": "Youthful",
        "nameZh": "少年感",
        "label": "少年感 (Youthful)",
        "items": [
          "Yeah!",
          "Whoa!",
          "Awesome!",
          "Here I go!",
          "No way!",
          "Hup!",
          "Let's do this!",
          "Got it!",
          "Hey!",
          "Woo!",
          "That was close!",
          "I can do it!",
          "Wait up!",
          "Cool!",
          "Watch me!",
          "Oops!",
          "All right!",
          "Really?!",
          "Ha!",
          "Not fair!"
        ]
      },
      {
        "id": "sub_8_4",
        "col": "D",
        "nameEn": "Elder / Wise",
        "nameZh": "长者 / 智者",
        "label": "长者 / 智者 (Elder / Wise)",
        "items": [
          "Hm.",
          "Patience.",
          "So it begins.",
          "Steady now.",
          "As expected.",
          "Hah.",
          "Listen closely.",
          "Not yet.",
          "You will learn.",
          "Careful.",
          "A familiar feeling.",
          "Enough.",
          "Observe.",
          "The old ways endure.",
          "Well then.",
          "Take your time.",
          "Do not rush.",
          "I see.",
          "Hmm.",
          "So be it."
        ]
      },
      {
        "id": "sub_8_5",
        "col": "E",
        "nameEn": "Soldier / Guard",
        "nameZh": "士兵 / 守卫",
        "label": "士兵 / 守卫 (Soldier / Guard)",
        "items": [
          "Hold the line!",
          "Advance!",
          "Move!",
          "Incoming!",
          "Fall back!",
          "For the unit!",
          "Cover me!",
          "On me!",
          "Stay sharp!",
          "Target spotted!",
          "Reloading!",
          "Go go go!",
          "Secure the area!",
          "Watch your flank!",
          "Take cover!",
          "Clear!",
          "Push forward!",
          "Enemy ahead!",
          "Hold!",
          "All clear!"
        ]
      },
      {
        "id": "sub_8_6",
        "col": "F",
        "nameEn": "Villain / Boss",
        "nameZh": "反派 / Boss",
        "label": "反派 / Boss (Villain / Boss)",
        "items": [
          "You dare?",
          "Kneel.",
          "Pathetic.",
          "This is my realm.",
          "You cannot win.",
          "Amuse me.",
          "Begone.",
          "I expected more.",
          "Your end is near.",
          "Fall before me.",
          "Fool.",
          "No mercy.",
          "Watch and despair.",
          "You are too late.",
          "I own this place.",
          "Try again.",
          "How quaint.",
          "Suffer.",
          "No escape.",
          "Goodbye."
        ]
      },
      {
        "id": "sub_8_7",
        "col": "G",
        "nameEn": "Civilian / Merchant",
        "nameZh": "平民 / 商人",
        "label": "平民 / 商人 (Civilian / Merchant)",
        "items": [
          "Hello there!",
          "Need something?",
          "Careful!",
          "Thank you!",
          "Oh my!",
          "Welcome!",
          "Please, look around.",
          "That's a fine choice.",
          "Help!",
          "Over here!",
          "What happened?",
          "Take care.",
          "Good day!",
          "No trouble, please.",
          "Fresh goods!",
          "Excuse me!",
          "Stay safe.",
          "My apologies.",
          "That'll do.",
          "Come again!"
        ]
      },
      {
        "id": "sub_8_8",
        "col": "H",
        "nameEn": "Wounded / Tired",
        "nameZh": "受伤 / 疲惫",
        "label": "受伤 / 疲惫 (Wounded / Tired)",
        "items": [
          "I'm hurt...",
          "Need a break...",
          "Not much left...",
          "Hah...",
          "Keep going...",
          "It burns...",
          "Give me a hand...",
          "Can't stop now...",
          "Just breathe...",
          "I'm okay...",
          "Almost there...",
          "This is rough...",
          "Need rest...",
          "Don't leave me...",
          "Still standing...",
          "Huff...",
          "One more step...",
          "I'm fading...",
          "Not done yet...",
          "Help me up..."
        ]
      }
    ]
  },
  {
    "id": "cat_9",
    "key": "Mechanical 机械",
    "title": "Mechanical 机械",
    "nameEn": "Mechanical",
    "nameZh": "机械",
    "emoji": "🤖",
    "description": "Robotic, powered-suit, device, and synthetic vocalizations and status calls. / 机器人、动力装甲、设备与合成角色的发声和状态播报。",
    "defaultInstruction": "机械合成质感，带有电子频响、舵机脉冲与数字合成器滤波效果。",
    "subcategories": [
      {
        "id": "sub_9_1",
        "col": "A",
        "nameEn": "Robot Beeps",
        "nameZh": "机器人提示音",
        "label": "机器人提示音 (Robot Beeps)",
        "items": [
          "Beep.",
          "Bweep!",
          "Bip-bip.",
          "Boop!",
          "Beep beep!",
          "Brrp.",
          "Bleep!",
          "Bwoo.",
          "Pip!",
          "Ding.",
          "Bip.",
          "Bloop!",
          "Brrt.",
          "Chirp.",
          "Pong.",
          "Pip-pip!",
          "Bzzz.",
          "Tick.",
          "Doot!",
          "Beep!"
        ]
      },
      {
        "id": "sub_9_2",
        "col": "B",
        "nameEn": "Servo / Motor",
        "nameZh": "舵机 / 电机",
        "label": "舵机 / 电机 (Servo / Motor)",
        "items": [
          "Whirr...",
          "Vrrrr...",
          "Krrrk.",
          "Click-clack.",
          "Bzzzt.",
          "Chnk.",
          "Whine...",
          "Rrrr...",
          "Tzzzt.",
          "Klak.",
          "Voom.",
          "Hummm.",
          "Grind...",
          "Chrrr.",
          "Thrum.",
          "Whirr-click.",
          "Zzzip.",
          "Krrr.",
          "Hmmm.",
          "Clunk."
        ]
      },
      {
        "id": "sub_9_3",
        "col": "C",
        "nameEn": "System Confirm",
        "nameZh": "系统确认",
        "label": "系统确认 (System Confirm)",
        "items": [
          "Confirmed.",
          "Acknowledged.",
          "Command received.",
          "Target acquired.",
          "Systems online.",
          "Ready.",
          "Affirmative.",
          "Engaging.",
          "Lock established.",
          "Processing.",
          "Complete.",
          "Access granted.",
          "Protocol active.",
          "Unit prepared.",
          "Route set.",
          "Signal received.",
          "Calibration complete.",
          "Standing by.",
          "Task accepted.",
          "Verified."
        ]
      },
      {
        "id": "sub_9_4",
        "col": "D",
        "nameEn": "Warning / Alarm",
        "nameZh": "警告 / 警报",
        "label": "警告 / 警报 (Warning / Alarm)",
        "items": [
          "Warning.",
          "Alert.",
          "Critical damage.",
          "Threat detected.",
          "System failure.",
          "Power low.",
          "Overheat.",
          "Intruder alert.",
          "Core unstable.",
          "Evacuate.",
          "Danger.",
          "Error.",
          "Shield failure.",
          "Hostile contact.",
          "Collision imminent.",
          "Battery critical.",
          "Alarm active.",
          "Hazard detected.",
          "Malfunction.",
          "Unauthorized access."
        ]
      },
      {
        "id": "sub_9_5",
        "col": "E",
        "nameEn": "Combat AI",
        "nameZh": "战斗 AI",
        "label": "战斗 AI (Combat AI)",
        "items": [
          "Engaging hostile.",
          "Firing.",
          "Weapon charged.",
          "Target eliminated.",
          "Reloading.",
          "Evasive maneuver.",
          "Defense protocol.",
          "Threat neutralized.",
          "Pursuit initiated.",
          "Scanning.",
          "Locking on.",
          "Impact confirmed.",
          "Deploying countermeasures.",
          "Range optimal.",
          "Attack pattern active.",
          "Hostile evaded.",
          "Weapon ready.",
          "Tracking target.",
          "Suppressing fire.",
          "Combat mode."
        ]
      },
      {
        "id": "sub_9_6",
        "col": "F",
        "nameEn": "Damage / Shutdown",
        "nameZh": "受损 / 关机",
        "label": "受损 / 关机 (Damage / Shutdown)",
        "items": [
          "Damage sustained.",
          "Integrity compromised.",
          "Error...",
          "Power failure.",
          "Shutdown imminent.",
          "Core breach.",
          "Motor jammed.",
          "Signal lost.",
          "Reboot required.",
          "Fault detected.",
          "Systems degrading.",
          "Unit disabled.",
          "Cannot comply.",
          "Critical malfunction.",
          "Power depleted.",
          "Memory corrupted.",
          "Emergency stop.",
          "Cooling failure.",
          "Connection severed.",
          "Offline."
        ]
      },
      {
        "id": "sub_9_7",
        "col": "G",
        "nameEn": "Synthetic Emotion",
        "nameZh": "合成情绪",
        "label": "合成情绪 (Synthetic Emotion)",
        "items": [
          "Curious.",
          "I calculate joy.",
          "Irritation detected.",
          "That is unexpected.",
          "I do not understand.",
          "Satisfaction recorded.",
          "Fear response simulated.",
          "This pleases me.",
          "Query: why?",
          "Humor detected.",
          "I object.",
          "Regret acknowledged.",
          "Fascinating.",
          "I am uncertain.",
          "Confidence high.",
          "Disappointment noted.",
          "Please clarify.",
          "That was enjoyable.",
          "I feel... strange.",
          "Observation complete."
        ]
      },
      {
        "id": "sub_9_8",
        "col": "H",
        "nameEn": "Radio / Comms",
        "nameZh": "无线电 / 通讯",
        "label": "无线电 / 通讯 (Radio / Comms)",
        "items": [
          "Copy that.",
          "Over.",
          "Signal weak.",
          "Say again.",
          "Receiving.",
          "Channel open.",
          "Static...",
          "Come in.",
          "Message received.",
          "Transmission ending.",
          "Loud and clear.",
          "Stand by.",
          "Connection established.",
          "Repeat.",
          "Negative.",
          "Roger.",
          "Out.",
          "Comms check.",
          "Broadcasting.",
          "Signal restored."
        ]
      }
    ]
  },
  {
    "id": "cat_10",
    "key": "UI / Reaction 界面 / 反应",
    "title": "UI / Reaction 界面 / 反应",
    "nameEn": "UI / Reaction",
    "nameZh": "界面 / 反应",
    "emoji": "🕹️",
    "description": "Short player-facing confirmations, menu sounds, notifications, and reactive cues. / 面向玩家的确认、菜单、通知与短促反应提示。",
    "defaultInstruction": "短促清晰、悦耳明快的系统与交互反馈拟声，节奏轻快利落。",
    "subcategories": [
      {
        "id": "sub_10_1",
        "col": "A",
        "nameEn": "Confirm / Select",
        "nameZh": "确认 / 选择",
        "label": "确认 / 选择 (Confirm / Select)",
        "items": [
          "Okay!",
          "Got it!",
          "Yes!",
          "Done!",
          "Confirmed.",
          "Let's go!",
          "Sure!",
          "Right!",
          "All set!",
          "Accepted.",
          "On it!",
          "Perfect!",
          "Sounds good!",
          "Ready!",
          "Select.",
          "There!",
          "Proceed.",
          "Fine by me!",
          "Absolutely!",
          "Go!"
        ]
      },
      {
        "id": "sub_10_2",
        "col": "B",
        "nameEn": "Cancel / Deny",
        "nameZh": "取消 / 拒绝",
        "label": "取消 / 拒绝 (Cancel / Deny)",
        "items": [
          "Nope.",
          "Not now.",
          "Can't do that.",
          "Denied.",
          "Try again.",
          "Unavailable.",
          "No.",
          "Cancel.",
          "That won't work.",
          "Locked.",
          "Not enough.",
          "Wrong choice.",
          "Access denied.",
          "Hold on.",
          "Stop.",
          "Invalid.",
          "Maybe later.",
          "No way.",
          "Blocked.",
          "Error."
        ]
      },
      {
        "id": "sub_10_3",
        "col": "C",
        "nameEn": "Discovery / Pickup",
        "nameZh": "发现 / 拾取",
        "label": "发现 / 拾取 (Discovery / Pickup)",
        "items": [
          "Oh!",
          "Nice!",
          "Found it!",
          "New item!",
          "Look at that!",
          "Got one!",
          "Treasure!",
          "Interesting.",
          "Aha!",
          "That's useful.",
          "Rare!",
          "Mine!",
          "What is this?",
          "Collected!",
          "Score!",
          "Lucky!",
          "Shiny!",
          "A secret!",
          "Excellent!",
          "Added."
        ]
      },
      {
        "id": "sub_10_4",
        "col": "D",
        "nameEn": "Mission / Objective",
        "nameZh": "任务 / 目标",
        "label": "任务 / 目标 (Mission / Objective)",
        "items": [
          "New objective.",
          "Mission updated.",
          "Let's move.",
          "Target marked.",
          "Next step.",
          "Task complete.",
          "Objective clear.",
          "We're close.",
          "Time to go.",
          "Route updated.",
          "Keep focused.",
          "Goal ahead.",
          "New lead.",
          "Track this.",
          "Progress saved.",
          "Checkpoint reached.",
          "Destination set.",
          "Make it happen.",
          "That's the plan.",
          "Onward."
        ]
      },
      {
        "id": "sub_10_5",
        "col": "E",
        "nameEn": "Success / Rank",
        "nameZh": "成功 / 评级",
        "label": "成功 / 评级 (Success / Rank)",
        "items": [
          "Excellent!",
          "Perfect!",
          "Great job!",
          "Mission complete!",
          "Level up!",
          "New record!",
          "Amazing!",
          "Flawless!",
          "Well done!",
          "S-rank!",
          "You did it!",
          "Bonus!",
          "Success!",
          "Outstanding!",
          "Clear!",
          "Nice work!",
          "Impressive!",
          "Victory!",
          "Achievement unlocked!",
          "Brilliant!"
        ]
      },
      {
        "id": "sub_10_6",
        "col": "F",
        "nameEn": "Failure / Retry",
        "nameZh": "失败 / 重试",
        "label": "失败 / 重试 (Failure / Retry)",
        "items": [
          "Try again.",
          "So close.",
          "Not quite.",
          "Failed.",
          "Let's retry.",
          "Don't give up.",
          "Almost had it.",
          "Back to it.",
          "Better luck next time.",
          "Mission failed.",
          "Reset.",
          "Keep trying.",
          "That didn't work.",
          "Start over.",
          "No worries.",
          "Learn and retry.",
          "One more time.",
          "Missed it.",
          "Come on.",
          "Again."
        ]
      },
      {
        "id": "sub_10_7",
        "col": "G",
        "nameEn": "Question / Prompt",
        "nameZh": "提问 / 提示",
        "label": "提问 / 提示 (Question / Prompt)",
        "items": [
          "Ready?",
          "Are you sure?",
          "Continue?",
          "Need help?",
          "Which way?",
          "What next?",
          "Want to proceed?",
          "Choose wisely.",
          "Confirm selection.",
          "Try this?",
          "Open it?",
          "Equip now?",
          "Leave area?",
          "Save progress?",
          "Accept quest?",
          "Use item?",
          "Start mission?",
          "Return to menu?",
          "Skip scene?",
          "Proceed?"
        ]
      },
      {
        "id": "sub_10_8",
        "col": "H",
        "nameEn": "Reaction / Surprise",
        "nameZh": "反应 / 惊讶",
        "label": "反应 / 惊讶 (Reaction / Surprise)",
        "items": [
          "Whoa!",
          "Hey!",
          "Oops!",
          "Huh?",
          "Ah!",
          "Really?",
          "Nice!",
          "Yikes!",
          "Oh no!",
          "Well done!",
          "Cool!",
          "Dang!",
          "Wait!",
          "Ha!",
          "No way!",
          "Phew!",
          "Uh-oh!",
          "Wow!",
          "Okay!",
          "Hmm..."
        ]
      }
    ]
  }
];

export function getCategoryById(id: string): GameVocalCategory | undefined {
  return GAME_VOCAL_CATEGORIES.find((c) => c.id === id);
}

export function getRandomItemsFromSubcategory(sub: GameVocalSubcategory, count: number): string[] {
  const shuffled = [...sub.items].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
